### ISSUE TITLE
Error line 61

### ISSUE THREAD

**Issue by bonelifer** [jfcarr-weather/current-weather#1]
When I run this with "KCXW" I get the below error. If I run it with another local airport "KHOT", it shows the weather. I checked the first ones feed online and it had data.
```
Traceback (most recent call last):
  File "current-weather.py", line 61, in <module>
    current_temperature = float(cw.get_element('temp_f'))
ValueError: could not convert string to float: 'N/A'

```

**Comment by jfcarr** [comment]
A "N/A" value in current temperature is now handled gracefully.
